---
steps:
  - id: Download Dependencies
    name: 'gcr.io/cloud-builders/mvn'
    dir: ${_SERVICE_NAME}
    args: [ 'dependency:go-offline' ]
  - id: Run Linting Checks
    name: 'docker.io/library/maven:3.8.3-openjdk-11'
    dir: ${_SERVICE_NAME}
    entrypoint: mvn
    args:
      - checkstyle:checkstyle
  - id: Run Unit Tests
    name: 'gcr.io/cloud-builders/mvn'
    dir: ${_SERVICE_NAME}
    args:
      - test
    env:
      - FACT_CHANGED_TOPIC="test-topic"
  - id: Build Container Image
    name: 'gcr.io/cloud-builders/mvn'
    dir: ${_SERVICE_NAME}
    args:
      - compile
      - com.google.cloud.tools:jib-maven-plugin:build
      - -Dimage=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:$COMMIT_SHA
  - id: Deploy to Cloud Run
    name: gcr.io/cloud-builders/gcloud:latest
    dir: ${_SERVICE_NAME}
    entrypoint: /bin/bash
    args:
      - -c
      - >
        gcloud run deploy ${_SERVICE_NAME} \
          --image ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:$COMMIT_SHA \
          --project ${_TARGET_PROJECT_ID} \
          --region ${_REGION} \
          --service-account=${_SERVICE_NAME}-sa@${_TARGET_PROJECT_ID}.iam.gserviceaccount.com \
          --update-env-vars PROJECT_ID=${_TARGET_PROJECT_ID},SERVICE_NAME=${_SERVICE_NAME},SPRING_PROFILES_ACTIVE='gcp',DATABASE_USER=${_FACT_DATABASE_USER},DATABASE_NAME=${_FACT_DATABASE_NAME},DATABASE_CONNECTION_NAME=${_TARGET_PROJECT_ID}:${_REGION}:${_FACT_DATABASE_INSTANCE},FACT_CHANGED_TOPIC=${_FACT_CHANGED_TOPIC},LOGGING_LEVEL_ORG_SKILLSMAPPER='DEBUG'
