apiVersion: skaffold/v4beta2
kind: Config
build:
  artifacts:
    - image: fact-service
      jib:
        fromImage: 'gcr.io/distroless/java:11'
manifests:
  rawYaml:
    - k8s/*.yaml
deploy:
  kubectl: { }
