swagger: "2.0"
info:
  title: skillsmapper
  description: Skills Mapper service
  version: 1.0.0
schemes:
  - "https"
consumes:
  - "application/json"
produces:
  - "application/json"
securityDefinitions:
  BearerAuth:
    type: "apiKey"
    name: "Authorization"
    in: "header"
    description: "Bearer token"
paths:
  /:
    get:
      summary: User Interface
      operationId: ui
      x-google-backend:
        address: https://user-interface-j7n5qulfna-uc.a.run.app
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /api-docs:
    get:
      summary: API Docs
      operationId: apiDocs
      x-google-backend:
        address: https://user-interface-j7n5qulfna-uc.a.run.app/api-docs
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /js/firebase.js:
    get:
      summary: User Interface
      operationId: firebasejs
      x-google-backend:
        address: https://user-interface-j7n5qulfna-uc.a.run.app/js/firebase.js
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /js/config.js:
    get:
      summary: User Interface
      operationId: configjs
      x-google-backend:
        address: https://user-interface-j7n5qulfna-uc.a.run.app/js/config.js
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /skills/autocomplete:
    get:
      summary: Autocomplete skills
      operationId: skillsAutocomplete
      description: Returns a list of skill suggestions based on the provided prefix
      x-google-backend:
        address: https://skill-lookup-j7n5qulfna-uc.a.run.app/autocomplete
      parameters:
        - name: prefix
          in: query
          description: The prefix to match against skill names
          required: true
          type: string
      produces:
        - "application/json"
      responses:
        200:
          description: A list of skill suggestions
          schema:
            type: array
            items:
              type: string
        400:
          description: Invalid request parameter(s)
        500:
          description: An unexpected error occurred
  /facts:
    get:
      summary: Get facts
      operationId: getFacts
      description: Get all facts for the authenticated user
      x-google-backend:
        address: https://fact-service-j7n5qulfna-uc.a.run.app/facts
      security:
        - BearerAuth: []
      produces:
        - "application/json"
      responses:
        200:
          description: A random fact
          schema:
            type: object
            properties:
              fact:
                type: string
                description: The random fact
        401:
          description: Unauthorized access
        500:
          description: An unexpected error occurred
    post:
      summary: Create a new fact
      description: Creates a new interesting fact for the provided skill and level
      operationId: postFacts
      x-google-backend:
        address: https://fact-service-j7n5qulfna-uc.a.run.app/facts
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "header"
          name: "Authorization"
          type: "string"
          description: "Bearer token"
          required: true
        - in: "body"
          name: "body"
          description: "The skill and level of the fact to create"
          required: true
          schema:
            type: "object"
            properties:
              skill:
                type: "string"
                description: "The skill for the fact"
              level:
                type: "string"
                description: "The level for the fact"
      responses:
        201:
          description: The newly created fact
          schema:
            type: "object"
            properties:
              fact:
                type: "string"
                description: The created fact
        400:
          description: Invalid request parameter(s)
        401:
          description: Unauthorized access
        500:
          description: An unexpected error occurred
