apiVersion: apps/v1
kind: Deployment
metadata:
  name: fact-service
  namespace: facts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fact-service
  template:
    metadata:
      labels:
        app: fact-service
    spec:
      serviceAccountName: facts-sa
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      containers:
        - name: fact-service
          image: $IMAGE
          env:
            - name: spring_profiles_active
              value: spanner
            - name: PROJECT_ID
              value: $PROJECT_ID
            - name: DATABASE_HOST
              value: "localhost"
            - name: DATABASE_PORT
              value: "5432"
          resources:
            requests:
              cpu: "0.5"
              memory: "1Gi"
          readinessProbe:
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            failureThreshold: 3
            httpGet:
              scheme: HTTP
              path: /actuator/health/readiness
              port: 8080
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
            failureThreshold: 3
            httpGet:
              scheme: HTTP
              path: /actuator/health/liveness
              port: 8080
        - name: pgadapter
          image: gcr.io/cloud-spanner-pg-adapter/pgadapter
          ports:
            - containerPort: 5432
          args:
            - "-p $PROJECT_ID"
            - "-i $SPANNER_INSTANCE"
            - "-d $SPANNER_DATABASE"
            - "-x"
          resources:
            requests:
              memory: "512Mi"
              cpu: "1"
