steps:
  - args:
      - build
      - gcr.io/$PROJECT_ID/skill-service
      - --network
      - cloudbuild
      - --builder
      - gcr.io/buildpacks/builder
    entrypoint: pack
    name: gcr.io/k8s-skaffold/pack
