apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
    - image: fact-service-k8s
      jib:
        fromImage: gcr.io/distroless/java17-debian11
manifests:
  rawYaml:
    - k8s/*.yaml
deploy:
  kubectl: {}
