apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: skill-service
build:
  artifacts:
    - image: skill-service
      ko: {}
manifests:
  rawYaml:
    - k8s/*.yaml
portForward:
  - resourceType: service
    resourceName: skill-service
    port: 8080
