apiVersion: v1
kind: Service
metadata:
  name: fact-service
  labels:
    app: fact-service
spec:
  ports:
    - port: 8080
      protocol: TCP
  clusterIP: None
  selector:
    app: fact-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fact-service
  labels:
    app: fact-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fact-service
  template:
    metadata:
      labels:
        app: fact-service
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: fact-service-sa-key
      containers:
        - name: fact-service
          image: fact-service
          envFrom:
            - configMapRef:
                name: fact-service-config
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/fact-service-sa.json
