apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: skill-service-dev
spec:
  template:
    spec:
      containers:
        - image: service
          resources:
            limits:
              cpu: 1000m
              memory: 128Mi
