apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: cloud-run-app
deploy:
  cloudrun: {}
profiles:
  - name: dev
    manifests:
      rawYaml:
        - deploy-dev.yaml
  - name: qa
    manifests:
      rawYaml:
        - deploy-qa.yaml
  - name: prod
    manifests:
      rawYaml:
        - deploy-prod.yaml
