swagger: "2.0"
info:
  title: citadel
  description: Sample API on API Gateway with a Cloud Run backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /:
    get:
      summary: Example Service
      operationId: exampleService
      x-google-backend:
        address: ${ui_service_url}
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /skill-lookup:
    get:
      summary: Example Service
      operationId: exampleService
      x-google-backend:
        address: ${example_service_url}
      responses:
        '200':
          description: A successful response
          schema:
            type: string
