apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fact-service-hpa
  namespace: facts
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fact-service
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
