apiVersion: v1
kind: Service
metadata:
  name: fact-service
  namespace: facts
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    app: fact-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
