steps:
  - id: check
    name: 'gcr.io/cloud-builders/curl'
    args: ['-s', '-H', 'Metadata-Flavor:Google', 'http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/email']
  - id: init
    name: 'hashicorp/terraform:1.5'
    dir: 'factory/terraform'
    args: [ 'init' ]
  - id: validate
    name: 'hashicorp/terraform:1.5'
    dir: 'factory/terraform'
    args: [ 'validate' ]
  - id: plan
    name: 'hashicorp/terraform:1.5'
    dir: 'factory/terraform'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        export TF_VAR_region="${_REGION}"
        export TF_VAR_app_installation_id="${_APP_INSTALLATION_ID}"
        export TF_VAR_github_repo="${_GITHUB_REPO}"
        export TF_VAR_github_token="${_GITHUB_TOKEN}"
        export TF_VAR_prefix="${_PREFIX}"
        export TF_VAR_domain="${_DOMAIN}"
        export TF_VAR_api_key="${_API_KEY}"
        export TF_VAR_billing_account="${_BILLING_ACCOUNT}"
        export TF_VAR_management_project_id="${_MANAGEMENT_PROJECT_ID}"
        export TF_VAR_dev_project_id="${_DEV_PROJECT_ID}"
        export TF_VAR_state_bucket="${_STATE_BUCKET}"
        terraform plan
  - id: apply
    name: 'hashicorp/terraform:1.5'
    dir: 'factory/terraform'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        export TF_VAR_region="${_REGION}"
        export TF_VAR_app_installation_id="${_APP_INSTALLATION_ID}"
        export TF_VAR_github_repo="${_GITHUB_REPO}"
        export TF_VAR_github_token="${_GITHUB_TOKEN}"
        export TF_VAR_prefix="${_PREFIX}"
        export TF_VAR_domain="${_DOMAIN}"
        export TF_VAR_api_key="${_API_KEY}"
        export TF_VAR_billing_account="${_BILLING_ACCOUNT}"
        export TF_VAR_management_project_id="${_MANAGEMENT_PROJECT_ID}"
        export TF_VAR_dev_project_id="${_DEV_PROJECT_ID}"
        export TF_VAR_state_bucket="${_STATE_BUCKET}"
        export TF_LOG=TRACE
        terraform apply -auto-approve
